name: dash
channels:
  - conda-forge
  - defaults
dependencies:
  - aws-c-auth=0.7.8=hcd8a21d_2
  - aws-c-cal=0.6.9=had988b7_2
  - aws-c-common=0.9.10=h10d778d_0
  - aws-c-compression=0.2.17=hb45f1eb_7
  - aws-c-event-stream=0.3.2=hbc2660c_8
  - aws-c-http=0.7.14=h1fa4523_3
  - aws-c-io=0.13.36=h3728bb0_2
  - aws-c-mqtt=0.9.10=h2150435_2
  - aws-c-s3=0.4.4=h960c460_0
  - aws-c-sdkutils=0.1.13=hb45f1eb_0
  - aws-checksums=0.1.17=hb45f1eb_6
  - aws-crt-cpp=0.24.11=hc04ff71_2
  - aws-sdk-cpp=1.11.210=h7d17a91_4
  - blinker=1.7.0=pyhd8ed1ab_0
  - bokeh=3.1.1=pyhd8ed1ab_0
  - brotli-python=1.1.0=py38h940360d_1
  - bzip2=1.0.8=h10d778d_5
  - c-ares=1.23.0=h10d778d_0
  - ca-certificates=2023.11.17=h8857fd0_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - contourpy=1.1.1=py38h15a1a5b_1
  - cytoolz=0.12.2=py38hcafd530_1
  - dash=2.14.2=pyhd8ed1ab_0
  - dash-core-components=2.0.0=pyhd8ed1ab_1
  - dash-html-components=2.0.0=pyhd8ed1ab_1
  - dash-mantine-components=0.9.0=pyhd8ed1ab_0
  - dash-table=5.0.0=pyhd8ed1ab_1
  - dask=2023.5.0=pyhd8ed1ab_0
  - dask-core=2023.5.0=pyhd8ed1ab_0
  - distributed=2023.5.0=pyhd8ed1ab_0
  - flask=3.0.0=pyhd8ed1ab_0
  - freetype=2.12.1=h60636b9_2
  - fsspec=2023.12.2=pyhca7485f_0
  - gflags=2.2.2=hb1e8313_1004
  - glog=0.6.0=h8ac2a54_0
  - icu=73.2=hf5e326d_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.0=pyha770c72_0
  - importlib_metadata=7.0.0=hd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - krb5=1.21.2=hb884880_0
  - lcms2=2.16=ha2f27b4_0
  - lerc=4.0.0=hb486fe8_0
  - libabseil=20230802.1=cxx17_h048a20a_0
  - libarrow=14.0.1=h7e6b3eb_9_cpu
  - libarrow-acero=14.0.1=hc222712_9_cpu
  - libarrow-dataset=14.0.1=hc222712_9_cpu
  - libarrow-flight=14.0.1=ha1803ca_9_cpu
  - libarrow-flight-sql=14.0.1=h8ec153b_9_cpu
  - libarrow-gandiva=14.0.1=heeebe7c_9_cpu
  - libarrow-substrait=14.0.1=h8ec153b_9_cpu
  - libblas=3.9.0=20_osx64_openblas
  - libbrotlicommon=1.1.0=h0dc2134_1
  - libbrotlidec=1.1.0=h0dc2134_1
  - libbrotlienc=1.1.0=h0dc2134_1
  - libcblas=3.9.0=20_osx64_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.5.0=h726d00d_0
  - libcxx=16.0.6=hd57cbcb_0
  - libdeflate=1.19=ha4e1b8e_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=13_2_0_h97931a8_1
  - libgfortran5=13.2.0=h2873a65_1
  - libgoogle-cloud=2.12.0=hc0857f6_4
  - libgrpc=1.59.3=ha7f534c_0
  - libiconv=1.17=hd75f5a5_1
  - libjpeg-turbo=3.0.0=h0dc2134_1
  - liblapack=3.9.0=20_osx64_openblas
  - libllvm15=15.0.7=hbedff68_4
  - libnghttp2=1.58.0=h64cf6d3_1
  - libopenblas=0.3.25=openmp_hfef2a42_0
  - libparquet=14.0.1=h27bd29f_9_cpu
  - libpng=1.6.39=ha978bb4_0
  - libprotobuf=4.24.4=h0ee05dc_0
  - libre2-11=2023.06.02=h4694dbf_0
  - libsqlite=3.44.2=h92b6c6a_0
  - libssh2=1.11.0=hd019ec5_0
  - libthrift=0.19.0=h064b379_1
  - libtiff=4.6.0=h684deea_2
  - libutf8proc=2.8.0=hb7f2c08_0
  - libwebp-base=1.3.2=h0dc2134_0
  - libxcb=1.15=hb7f2c08_0
  - libxml2=2.12.3=hc0ae0f7_0
  - libzlib=1.2.13=h8a1eda9_5
  - llvm-openmp=17.0.6=hb6ac08f_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.2=py38h8021d85_1
  - lz4-c=1.9.4=hf0c8a7f_0
  - markupsafe=2.1.3=py38hcafd530_1
  - msgpack-python=1.0.7=py38ha94643f_0
  - ncurses=6.4=h93d8f39_2
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - numpy=1.24.4=py38h9a4a08f_0
  - openjpeg=2.5.0=ha4da562_3
  - openssl=3.2.0=hd75f5a5_1
  - orc=1.9.2=h9ab30d4_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.0.3=py38h78e6021_1
  - partd=1.4.1=pyhd8ed1ab_0
  - pillow=10.1.0=py38h0024655_0
  - pip=23.3.1=pyhd8ed1ab_0
  - plotly=5.18.0=pyhd8ed1ab_0
  - psutil=5.9.5=py38hcafd530_1
  - pthread-stubs=0.4=hc929b4f_1001
  - pyarrow=14.0.1=py38hffdeace_9_cpu
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.18=h5ba8234_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.8=4_cp38
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py38hcafd530_1
  - re2=2023.06.02=hd34609a_0
  - readline=8.2=h9e318b2_1
  - requests=2.31.0=pyhd8ed1ab_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h225ccf5_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - tk=8.6.13=h1abcd95_1
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.3=py38hcafd530_1
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=h0dc2134_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.5=h829000d_0
  - pip:
    - ansi2html==1.8.0
    - dash-bootstrap-components==1.5.0
    - retrying==1.3.4
prefix: /opt/anaconda3/envs/dash
